name: Build binary for MacOS
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - name: List python packages
        run: |
          python -m pip list
        shell: bash
      
      # 没有可用的mac-upx版本，先就这样吧，等我先写好自动构建
      - name: prepare upx module
        run: |
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-win64.zip 
          unzip upx-3.96-win64.zip
        shell: bash
        
      - name: repair pyinstaller subprocess caller compat
        run: |
          old="proc.communicate(timeout=60)"
          new="proc.communicate(timeout=600)"
          path="${{ env.pythonLocation }}/lib/Python3.9/site-packages/PyInstaller/compat.py"
          sed -i "" "s/$old/$new/" $path
        shell: bash

      - name: Build execuate
        run: |
          upx=$(cd "$(dirname "$0")"; pwd -P)
          chmod +x ./build/MacOS.sh
          ./build/MacOS.sh -upx $upx
        shell: bash

      - name: Upload asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/tmp/dist/KnightReport.dmg
          tag_name: automatic

    #     - name: Auth to gitlab
    #       env:
    #           TOKEN: ${{ secrets.GITLAB_TOKEN }}
    #       run: |
    #         curl --header "PRIVATE-TOKEN: $TOKEN" "https://gitlab.com/api/v4/projects/29590976"

#     - name: Upload asset to gitlab
#       env:
#           TOKEN: ${{ secrets.GITLAB_TOKEN }}
#       run: |
#         curl --header "PRIVATE-TOKEN: $TOKEN" \
#         --upload-file "dist/windows/KnightReport.exe" \
#         "https://gitlab.com/api/v4/projects/29590976/packages/generic/KnightReport/automatic/KnightReport.exe?status=default"
