name: Build binary for MacOS
on:
  push:
    branches: [ main ]
      
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - name: List python packages
        run: |
          python -m pip list
        shell: bash
      
      - name: prepare upx module
        run: |
          brew install upx
        shell: bash

      - name: Build execuate
        run: |
          upx="$(brew --prefix upx)/bin"
          echo "upx is installed at $upx"
          chmod +x ./build/MacOS.sh
          ./build/MacOS.sh $upx
        shell: bash

      - name: Upload asset to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/tmp/KnightReport-mac.dmg
          tag_name: automatic

      - name: Auth to gitlab
        env:
          TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          curl --header "PRIVATE-TOKEN: $TOKEN" "https://gitlab.com/api/v4/projects/29590976"

      - name: Upload asset to gitlab
        env:
          TOKEN: ${{ secrets.GITLAB_TOKEN }}
          PATH: ${{ github.workspace }}/tmp/KnightReport-mac.dmg
        run: |
          curl --header "PRIVATE-TOKEN: $TOKEN" \
          --upload-file "$PATH" \
          "https://gitlab.com/api/v4/projects/29590976/packages/generic/KnightReport/automatic/KnightReport-mac.dmg?status=default"
