name: Clear assets inside automatic
on:
  push:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete current release assets
        uses: andreaswilli/delete-release-assets-action@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: automatic
