name: Run static check

on:
  push:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: pylinter
        uses: alexanderdamiani/pylinter@v1.3.0
        with:
          # directory to run linting on
          python-root: './src'
          # flake8 flags
          flake8-flags: .
          # mypy flags
          mypy-flags: .
          # optional exit on isort errors
          fail-on-isort: true
          # skip flake8 checks
          skip-flake8: false
          # skip mypy checks
          skip-mypy: false
          # skip isort checks
          skip-isort: false

