name: Run static check

on:
  push:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Analysing the code with pylint
        uses: konstruktoid/action-pylint@master
 
