name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
          
      - name: List python packages
        run: |
          python -m pip list
          
      - name: Python unit tests
        run: |
          python -m unittest
